server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: ariss-log-action-test-application
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: log_action_test
        use_sql_comments: true
        format_sql: true
  datasource:
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:postgresql://localhost:5432/unit_techno?currentSchema=log_action_test
    username: log_admin
    password: squd