server:
  port: 8080

spring:
  application:
    name: ariss-log-action-test-application
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: log_action_test
        use_sql_comments: true
        format_sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/unit_techno?currentSchema=log_action_test
    username: log_admin
    password: squd